# Default values for fort application

# Global configuration
global:
  environment: production

# Frontend configuration
frontend:
  image: maxxa/front_fort_bloc
  tag: latest
  port: 80
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Proxy configuration
proxy:
  image: maxxa/proxy_fort_bloc
  tag: latest
  port: 3000
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Ingress configuration
ingress:
  enabled: true
  host: k0li.fr
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure