# Default values for fort.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccount:
  create: false

proxy:
  image: maxxa/proxy_fort_bloc
  tag: "latest"
  service:
    port: 3000

frontend:
  image: maxxa/front_fort_bloc
  tag: "latest"
  service:
    port: 80

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  enabled: false
  allowPrivilegeEscalation: true
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: k0li.fr
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

resources:
  limits:
    cpu: 200m
    memory: 228Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}