apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.proxy.image }}:{{ .Values.proxy.tag }}"
          ports:
            - containerPort: {{ .Values.proxy.port }}
          resources:
          {{- toYaml .Values.proxy.resources | nindent 10 }}
          readinessProbe:
            httpGet:
              path: /api/meteo
              port: {{ .Values.proxy.port }}
            initialDelaySeconds: 5
            periodSeconds: 10