apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fort.fullname" . }}
  labels:
    {{- include "fort.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      front-{{- include "fort.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        front-{{- include "fort.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: front-{{ .Chart.Name }}
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-{{ include "fort.fullname" . }}
  labels:
    proxy-{{- include "fort.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      proxy-{{- include "fort.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        proxy-{{- include "fort.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy-{{ .Chart.Name }}
          image: "{{ .Values.proxy.image }}:{{ .Values.proxy.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
                    {{- toYaml .Values.resources | nindent 12 }}